#!/bin/bash
echo "Пожалуйста, введите сид-фразу для кошелька, используемого в работе."
read -s SEED_PHRASE  # Добавляем -s для скрытия ввода

echo "Введите URL RPC сервера:"
read -p "RPC URL: " RPC_URL

WORK_DIR="$HOME/allora-workers"
mkdir -p $WORK_DIR && cd $WORK_DIR

echo "Останавливаем и удаляем существующие контейнеры..."
docker compose -f $WORK_DIR/allora-huggingface-walkthrough/docker-compose.yaml down -v

echo "Удаляем старые данные..."
rm -rf basic-coin-prediction-node

WORKER_VERSIONS=("worker1-10m" "worker2-24h" "worker3-20m")
REPO_URL="https://github.com/nhunamit/basic-coin-prediction-node.git"

for VERSION in "${WORKER_VERSIONS[@]}"; do
    echo "------------- Установка $VERSION -------------"
    git clone $REPO_URL
    mv basic-coin-prediction-node $VERSION
    cd $VERSION
    git checkout $VERSION
    sed -i "/\"nodeRpc\"/ s|\"nodeRpc\": \".*\"|\"nodeRpc\": \"$RPC_URL\"|" config.json
    sed -i "s|just clap slim ...|$SEED_PHRASE|" config.json
    ./init.config
    docker compose build
    docker compose up -d
    cd ..
done

echo "Все воркеры установлены. Логи:"
for VERSION in "${WORKER_VERSIONS[@]}"; do
    echo "Логи для $VERSION:"
    docker compose -f $WORK_DIR/$VERSION/docker-compose.yml logs -f -n 10
done
